### ISSUE TITLE
Why the <span> wrap?

### ISSUE THREAD

**Issue by tsi** [rubenv/angular-gettext#191] opened 2015-05-10 15:30 UTC
I can see you wrap the translated string in a `<span>`, e.g. -
`key = angular.element('<span>' + key + '</span>').html();`

Why is that? can we opt-out of it?
The problem is that it can break the html layout in more then one way, and maybe even produce invalid html where spans are not allowed.

**Comment by rubenv** [comment] 2015-05-10 17:21
It doesn't. Note the .html() at the end of the line, which takes the contents of the span.

That line is there for IE, which has some specific bugs related to how it handles HTML.

Any new span elements you see are caused by Angular itself, when it creates a new scope.

**Comment by tsi** [comment] 2015-05-11 07:58
Thanks for the quick reply.
You're right. that line has nothing to do with the ````<span>````s I'm seeing.

But if, later on (around line 193), insted of:
````
var newWrapper = angular.element('<span>' + translated + '</span>');
$compile(newWrapper.contents())(scope);
````
I do:
````
var newWrapper = $compile(angular.element(document.createTextNode(translated)))(scope);
````
I get the behavior I want - that is, text is being replaced with text, without any wrapper. since I'm compiling a text node and not a span element.
Do you know of any drawbacks to this method?

**Comment by rubenv** [comment] 2015-05-11 08:19
Yes, it only works with text nodes, not with anything that has markup
inside.

It appears that you are running into some kind of problem, but you are
focusing on what you think is the solution.

Let's start with the diagnose rather than a proposed solution. What is it
that you are trying to do, which doesn't work?

**Comment by tsi** [comment] 2015-05-11 08:34
It's pretty simple - we have a working product and we are now adding l10n capabilities, the addition of the ````<span>````s breaks stuff in my layout. This is caused by some CSS rules that are created by the framework we're using (Ionic).
Dealing with this via CSS is easy, will take just a few overrides, but I thought it will be safer to just make sure the markup remains the same after translation, this way I don't have to worry about the CSS.

> Yes, it only works with text nodes, not with anything that has markup inside.

That might be a good thing - I would argue that no html should be passed to translation, unless you want your layout to break (on specific languages only) because your translator missed a ````/```` by accident.

**Comment by rubenv** [comment] 2015-05-11 09:28
Do you have an example of where things break (a jsFiddle or so)? There's plenty of people using Ionic (including myself) combined with angular-gettext.

Extra spans shouldn't break your layout, not if your CSS is somewhat decent.

**Comment by tsi** [comment] 2015-05-11 12:11
There ya go - http://codepen.io/tsi/pen/QbyxJm/
Keep in mind that this is just an example, this problem can manifest itself in many different ways, most of them relate to CSS authoring, but not necessarily.

**Comment by rubenv** [comment] 2015-05-11 12:22
Oh yes that. Well, I consider that a CSS bug. No CSS rule should be so general that it lays claim to the sole ownership of `span` or `div`. 

If it helps, you can use `ng-scope` as a detection mechanism to figure out which spans were generated by Angular.

Either way, I'd rather not go and hack around to avoid the Angular-generated scope spans. We've tried it before, it failed in many ways. Any directive suffers from this problem, not just this one.

**Comment by circlingthesun** [comment] 2015-05-11 12:31
I was not aware that one could get around these spans. What would using ```document.createTextNode()``` only on text nodes break?

**Comment by tsi** [comment] 2015-05-11 12:32
I understand.
Yet, I do believe that a translation component should be only replacing text with text on one hand, and that the human translator should never have html as part of the string-to-be-translated on the other hand. so I might take that route myself and use the ````document.createTextNode()```` approach.
Could you point me at any other fail points I might encounter?

**Comment by circlingthesun** [comment] 2015-05-11 12:39
@tsi, When you only deal with plain text creates other problems. For example, if you have a link in your text you translator will be presented with 3 text fragments and no context. Translating these fragments separately may result in a bad translation when combined.

**Comment by tsi** [comment] 2015-05-11 13:12
Yes, but the link will always work. passing html in the translated string risk it being broken on certain languages, while working on others - a QA nightmare.

**Comment by tsi** [comment] 2015-05-11 13:18
Regarding context, this can be easily mitigated with comments.

Like you, I *would* rather having the ability to insert html (when absolutely necessary), but if the price is an extra sneaky span for every translated string, I think I'd rather the context issue then the extra span.

If we could have both that would be better, though.

**Comment by enapupe** [comment] 2015-07-03 18:23
+1 to this issue, the extra span tag is bad resolution.
Why do we need this?

**Comment by enapupe** [comment] 2015-07-03 18:37
What happens if we don't `$compile(newWrapper.contents())(scope);` ? What is the use case for this compilation? I have a test scenario with strings only and it work just fine..

**Comment by JoMas971** [comment] 2015-09-18 09:31
+1 to this issue. The other thing when you adding a span wrapper for each translation strings is that you multiply the number of DOM element for the browser to deal with. When you have a big application with a lot of data (i.e : infinite scrolling app) you can feel performance issues at some point. Specially when you have a not powerful laptop/computer and using chrome.

**Comment by rubenv** [comment] 2015-09-18 09:45
@JoMas971 that's the wrong optimisation to make: if you want to do infinite scrolling, do it properly and only render the elements in view. For a good example of how to do it, see how SlickGrid does it: half a million rows with no problems at all: http://mleibman.github.io/SlickGrid/examples/example-optimizing-dataview.html

Anything else will gain you a few %, but will never really solve the scaling issue. There will always be a point where it becomes "too much" if you render the whole page all the time.

**Comment by enapupe** [comment] 2015-09-18 13:56
@rubenv i think we are going out of focus here.. I believe there are other issue regarding performance, two/one way binding and stuff like this..

I believe the main reasons to not add this span tag is because of the possibility of breaking CSS code and also translation plugins are not expected to mess up with our markup..  How does angular i18n works?

I'm seeing myself using interpolation instead the directive since I found out the directive adds an extra span tag.. Which way performs better? Do you have any kind of benchmark? 
Thanks for your time.

**Comment by rubenv** [comment] 2015-09-18 14:18
> What happens if we don't $compile(newWrapper.contents())(scope); ? What is the use case for this compilation?

It breaks interpolation: variable substitution won't work anymore.

We've tried in the past to work around the spans by avoiding standard transclusion: it always ended up leading to a huge pile of bugs. Nowadays we use the standard mechanism provided by Angular.JS. While it's not very pretty, it does work flawlessly.

If someone really wants to get rid of the extra spans and finds a clean (and performant) way: go for it and feel free to send a pull request.

But before you start down this route, please be warned that a) you'll probably break things, which won't be acceptable and b) if you think you can do better (faster, cleaner) than the Angular.JS team, why not help them fix the way scopes are generated? I'm sure many places will benefit from this improvement.

Angular-gettext isn't doing anything special compared to e.g. `ng-if`. Any strange behavior is just plain old Angular behavior.

**Comment by mpiasta-ca** [comment] 2016-02-03 22:11
Just came across this `<span>` problem!

If you use a translate directive for the `<title>` element, it fails to display the title in browser because it's wrapped in a `<span>` :tired_face: 

If I use a filter instead, I'm unable to set a context, and as well the title appears broken until the JavaScript is rendered, which is likely undesirable for search engine indexing as well.

**Comment by enapupe** [comment] 2016-02-03 23:47
Can't you pass the context to this filter? From the source code:
```
angular.module('gettext').filter('translate', function (gettextCatalog) {
    function filter(input, context) {
        return gettextCatalog.getString(input, null, context);
    }
    filter.$stateful = true;
    return filter;
});
``` 

SO, you can `{{ "some string" | translate: "somecontext" }}`

**Comment by mpiasta-ca** [comment] 2016-02-04 18:08
@enapupe see issue #261.

**Comment by enapupe** [comment] 2016-02-04 18:10
Well.. that's a shame. Clearly a bug that must be killed!

**Comment by aachurin** [comment] 2016-02-12 06:54
This should help:

```
// Avoid redundant swaps
if (translated === trim(element.html())){ // using oldContents.html() is wrong
    // Take care of unlinked content
    if (linking){
        var content = $compile(oldContents)(scope);
        element.append(content.contents());
        content.remove();
    }
    return;
}

// Swap in the translation
var newWrapper = angular.element('<span>' + translated + '</span>');
$compile(newWrapper)(scope);
var newContents = newWrapper.contents();
$animate.enter(newContents, element);
$animate.leave(oldContents);
newWrapper.remove();
```

**Comment by aachurin** [comment] 2016-03-07 22:34
maybe i need to make a pull request?

**Comment by svift** [comment] 2016-04-30 12:27
My site was working weirdly after adding this module and I found the culprit to be the extra span (I'm using angular material). The extra span tags are causing lot of CSS problems (like width, font color, etc) for me.

The solution proposed by @aachurin seems to be working fine for me now (I copy pasted it for now). But does it pass all tests and will it be merged in later versions?

**Comment by minutephp** [comment] 2016-07-13 01:23
Hi,

I'm still getting the extra &lt;span&gt; tag in the latest version ("^2.3.4": I'm installing using bower). The extra span is really breaking our whole site but if I copy-paste the code above by `aachurin`, everything starts to work perfectly!

Anyway, how can I get the version with the fixes done by @aachurin using bower install? Because I'm guessing the changes I made by hand will revert during deployment. 

Please help.

**Comment by sbrunner** [comment] 2016-07-14 13:27
+1 this is a big issue we have with this...

**Comment by minutephp** [comment] 2016-07-14 13:30
@sbrunner: Here is a workaround I have while the PR by @aachurin is merged in the main code.

Update your bower.json with the following code:

````
  "dependencies": {
    "angular-gettext": "aitarget/angular-gettext#b23504fdc21df55fbbfc23875227e1a64ee61077",
````

**Comment by enapupe** [comment] 2016-07-14 13:33
@minutephp Could you please link such PR? I couldn't find any.

**Comment by minutephp** [comment] 2016-07-14 14:47
@enapupe i couldn't find the PR by @aachurin so I forked the repo and added the code above. The PR is here: https://github.com/rubenv/angular-gettext/issues/299

**Comment by circlingthesun** [comment] 2016-12-09 16:28
Angular 1.6 fixes the span issue. See:
Spans in 1.5.9: http://plnkr.co/edit/tKloB8LFk3GCAsu0UEUx?p=preview
No spans in 1.6.0: http://plnkr.co/edit/tE96QrOPtqxuxR4xbxRL?p=preview

**Closed** 2016-12-10 15:46 UTC
